import boto3
from .config import AWS_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY

s3_client = boto3.client('s3',region_name=AWS_REGION,aws_access_key_id=AWS_ACCESS_KEY_ID,aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
sqs_client=boto3.client('sqs',region_name=AWS_REGION,aws_access_key_id=AWS_ACCESS_KEY_ID,aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
dynamodb_client=boto3.client('dynamodb',region_name=AWS_REGION,aws_access_key_id=AWS_ACCESS_KEY_ID,aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
glue_client=boto3.client('glue',region_name=AWS_REGION,aws_access_key_id=AWS_ACCESS_KEY_ID,aws_secret_access_key=AWS_SECRET_ACCESS_KEY)